### ISSUE TITLE
Repo name could be better

### ISSUE THREAD

**Issue by thujone** [carabus/quiz-app-jquery#1]
A fine point here, and I don't think you should change your repo name. But 'quiz-app' is a better name than 'quiz-app-jquery'. Generally, you want to name things for what they are, not for what technologies may be used with it. If you really want 'jquery' as a part of the name, it would be clearer to name it 'jquery-quiz-app' where essentially 'jquery' is a noun used as an adjective to describe the quiz app.

**Comment by carabus** [comment]
not going to fix at this time but will make a note for next time.
