### ISSUE TITLE
ES6 forEach()

### ISSUE THREAD

**Issue by thujone** [carabus/quiz-app-jquery#8]
https://github.com/carabus/quiz-app-jquery/blob/cc18953ca80cadb55f1f3b24b06c0bb246c7fd88/index.js#L29

'For' loops like this one are kind of old-fashioned in ES6. Try to use .forEach() instead, or else .map() or .filter().

**Comment by carabus** [comment]
I am not so sure foreach is appropriate in this case as we are moving elements within the array.
